<?php
// count 142
return array(
    "af" => array("name" => "Afrikaans", "native" => "Afrikaans", "id" => 1),
    "sq" => array("name" => "Albanian - shqip", "native" => "shqip", "id" => 2),
    "am" => array("name" => "Amharic - አማርኛ", "native" => "አማርኛ", "id" => 3),
    "ar" => array("name" => "Arabic - العربية", "native" => "العربية", "id" => 4),
    "an" => array("name" => "Aragonese - aragonés", "native" => "aragonés", "id" => 5),
    "hy" => array("name" => "Armenian - հայերեն", "native" => "հայերեն", "id" => 6),
    "ast" => array("name" => "Asturian - asturianu", "native" => "asturianu", "id" => 7),
    "az" => array("name" => "Azerbaijani - azərbaycan dili", "native" => "azərbaycan dili", "id" => 8),
    "eu" => array("name" => "Basque - euskara", "native" => "euskara", "id" => 9),
    "be" => array("name" => "Belarusian - беларуская", "native" => "беларуская", "id" => 10),
    "bn" => array("name" => "Bengali - বাংলা", "native" => "বাংলা", "id" => 11),
    "bs" => array("name" => "Bosnian - bosanski", "native" => "bosanski", "id" => 12),
    "br" => array("name" => "Breton - brezhoneg", "native" => "brezhoneg", "id" => 13),
    "bg" => array("name" => "Bulgarian - български", "native" => "български", "id" => 14),
    "ca" => array("name" => "Catalan - català", "native" => "català", "id" => 15),
    "ckb" => array("name" => "Central Kurdish - کوردی (دەستنوسی عەرەبی)", "native" => "کوردی (دەستنوسی عەرەبی)", "id" => 16),
    "zh" => array("name" => "Chinese - 中文", "native" => "中文", "id" => 17),
    "zh-HK" => array("name" => "Chinese (Hong Kong) - 中文（香港）", "native" => "中文（香港）", "id" => 18),
    "zh-CN" => array("name" => "Chinese (Simplified) - 中文（简体）", "native" => "中文（简体）", "id" => 19),
    "zh-TW" => array("name" => "Chinese (Traditional) - 中文（繁體）", "native" => "中文（繁體）", "id" => 20),
    "co" => array("name" => "Corsican", "native" => "Corsican", "id" => 21),
    "hr" => array("name" => "Croatian - hrvatski", "native" => "hrvatski", "id" => 22),
    "cs" => array("name" => "Czech - čeština", "native" => "čeština", "id" => 23),
    "da" => array("name" => "Danish - dansk", "native" => "dansk", "id" => 24),
    "nl" => array("name" => "Dutch - Nederlands", "native" => "Nederlands", "id" => 25),
    "en" => array("name" => "English", "native" => "English", "id" => 26),
    "en-AU" => array("name" => "English (Australia)", "native" => "English (Australia)", "id" => 27),
    "en-CA" => array("name" => "English (Canada)", "native" => "English (Canada)", "id" => 28),
    "en-IN" => array("name" => "English (India)", "native" => "English (India)", "id" => 29),
    "en-NZ" => array("name" => "English (New Zealand)", "native" => "English (New Zealand)", "id" => 30),
    "en-ZA" => array("name" => "English (South Africa)", "native" => "English (South Africa)", "id" => 31),
    "en-GB" => array("name" => "English (United Kingdom)", "native" => "English (United Kingdom)", "id" => 32),
    "en-US" => array("name" => "English (United States)", "native" => "English (United States)", "id" => 33),
    "eo" => array("name" => "Esperanto - esperanto", "native" => "esperanto", "id" => 34),
    "et" => array("name" => "Estonian - eesti", "native" => "eesti", "id" => 35),
    "fo" => array("name" => "Faroese - føroyskt", "native" => "føroyskt", "id" => 36),
    "fil" => array("name" => "Filipino", "native" => "Filipino", "id" => 37),
    "fi" => array("name" => "Finnish - suomi", "native" => "suomi", "id" => 38),
    "fr" => array("name" => "French - français", "native" => "français", "id" => 39),
    "fr-CA" => array("name" => "French (Canada) - français (Canada)", "native" => "français (Canada)", "id" => 40),
    "fr-FR" => array("name" => "French (France) - français (France)", "native" => "français (France)", "id" => 41),
    "fr-CH" => array("name" => "French (Switzerland) - français (Suisse)", "native" => "français (Suisse)", "id" => 42),
    "gl" => array("name" => "Galician - galego", "native" => "galego", "id" => 43),
    "ka" => array("name" => "Georgian - ქართული", "native" => "ქართული", "id" => 44),
    "de" => array("name" => "German - Deutsch", "native" => "Deutsch", "id" => 45),
    "de-AT" => array("name" => "German (Austria) - Deutsch (Österreich)", "native" => "Deutsch (Österreich)", "id" => 46),
    "de-DE" => array("name" => "German (Germany) - Deutsch (Deutschland)", "native" => "Deutsch (Deutschland)", "id" => 47),
    "de-LI" => array("name" => "German (Liechtenstein) - Deutsch (Liechtenstein)", "native" => "Deutsch (Liechtenstein)", "id" => 48),
    "de-CH" => array("name" => "German (Switzerland) - Deutsch (Schweiz)", "native" => "Deutsch (Schweiz)", "id" => 49),
    "el" => array("name" => "Greek - Ελληνικά", "native" => "Ελληνικά", "id" => 50),
    "gn" => array("name" => "Guarani", "native" => "Guarani", "id" => 51),
    "gu" => array("name" => "Gujarati - ગુજરાતી", "native" => "ગુજરાતી", "id" => 52),
    "ha" => array("name" => "Hausa", "native" => "Hausa", "id" => 53),
    "haw" => array("name" => "Hawaiian - ʻŌlelo Hawaiʻi", "native" => "ʻŌlelo Hawaiʻi", "id" => 54),
    "he" => array("name" => "Hebrew - עברית", "native" => "עברית", "id" => 55),
    "hi" => array("name" => "Hindi - हिन्दी", "native" => "हिन्दी", "id" => 56),
    "hu" => array("name" => "Hungarian - magyar", "native" => "magyar", "id" => 57),
    "is" => array("name" => "Icelandic - íslenska", "native" => "íslenska", "id" => 58),
    "id" => array("name" => "Indonesian - Indonesia", "native" => "Indonesia", "id" => 59),
    "ia" => array("name" => "Interlingua", "native" => "Interlingua", "id" => 60),
    "ga" => array("name" => "Irish - Gaeilge", "native" => "Gaeilge", "id" => 61),
    "it" => array("name" => "Italian - italiano", "native" => "italiano", "id" => 62),
    "it-IT" => array("name" => "Italian (Italy) - italiano (Italia)", "native" => "italiano (Italia)", "id" => 63),
    "it-CH" => array("name" => "Italian (Switzerland) - italiano (Svizzera)", "native" => "italiano (Svizzera)", "id" => 64),
    "ja" => array("name" => "Japanese - 日本語", "native" => "日本語", "id" => 65),
    "kn" => array("name" => "Kannada - ಕನ್ನಡ", "native" => "ಕನ್ನಡ", "id" => 66),
    "kk" => array("name" => "Kazakh - қазақ тілі", "native" => "қазақ тілі", "id" => 67),
    "km" => array("name" => "Khmer - ខ្មែរ", "native" => "ខ្មែរ", "id" => 68),
    "ko" => array("name" => "Korean - 한국어", "native" => "한국어", "id" => 69),
    "ku" => array("name" => "Kurdish - Kurdî", "native" => "Kurdî", "id" => 70),
    "ky" => array("name" => "Kyrgyz - кыргызча", "native" => "кыргызча", "id" => 71),
    "lo" => array("name" => "Lao - ລາວ", "native" => "ລາວ", "id" => 72),
    "la" => array("name" => "Latin", "native" => "Latin", "id" => 73),
    "lv" => array("name" => "Latvian - latviešu", "native" => "latviešu", "id" => 74),
    "ln" => array("name" => "Lingala - lingála", "native" => "lingála", "id" => 75),
    "lt" => array("name" => "Lithuanian - lietuvių", "native" => "lietuvių", "id" => 76),
    "mk" => array("name" => "Macedonian - македонски", "native" => "македонски", "id" => 77),
    "ms" => array("name" => "Malay - Bahasa Melayu", "native" => "Bahasa Melayu", "id" => 78),
    "ml" => array("name" => "Malayalam - മലയാളം", "native" => "മലയാളം", "id" => 79),
    "mt" => array("name" => "Maltese - Malti", "native" => "Malti", "id" => 80),
    "mr" => array("name" => "Marathi - मराठी", "native" => "मराठी", "id" => 81),
    "mn" => array("name" => "Mongolian - монгол", "native" => "монгол", "id" => 82),
    "ne" => array("name" => "Nepali - नेपाली", "native" => "नेपाली", "id" => 83),
    "no" => array("name" => "Norwegian - norsk", "native" => "norsk", "id" => 84),
    "nb" => array("name" => "Norwegian Bokmål - norsk bokmål", "native" => "norsk bokmål", "id" => 85),
    "nn" => array("name" => "Norwegian Nynorsk - nynorsk", "native" => "nynorsk", "id" => 86),
    "oc" => array("name" => "Occitan", "native" => "Occitan", "id" => 87),
    "or" => array("name" => "Oriya - ଓଡ଼ିଆ", "native" => "ଓଡ଼ିଆ", "id" => 88),
    "om" => array("name" => "Oromo - Oromoo", "native" => "Oromoo", "id" => 89),
    "ps" => array("name" => "Pashto - پښتو", "native" => "پښتو", "id" => 90),
    "fa" => array("name" => "Persian - فارسی", "native" => "فارسی", "id" => 91),
    "pl" => array("name" => "Polish - polski", "native" => "polski", "id" => 92),
    "pt" => array("name" => "Portuguese - português", "native" => "português", "id" => 93),
    "pt-BR" => array("name" => "Portuguese (Brazil) - português (Brasil)", "native" => "português (Brasil)", "id" => 94),
    "pt-PT" => array("name" => "Portuguese (Portugal) - português (Portugal)", "native" => "português (Portugal)", "id" => 95),
    "pa" => array("name" => "Punjabi - ਪੰਜਾਬੀ", "native" => "ਪੰਜਾਬੀ", "id" => 96),
    "qu" => array("name" => "Quechua", "native" => "Quechua", "id" => 97),
    "ro" => array("name" => "Romanian - română", "native" => "română", "id" => 98),
    "mo" => array("name" => "Romanian (Moldova) - română (Moldova)", "native" => "română (Moldova)", "id" => 99),
    "rm" => array("name" => "Romansh - rumantsch", "native" => "rumantsch", "id" => 100),
    "ru" => array("name" => "Russian - русский", "native" => "русский", "id" => 101),
    "gd" => array("name" => "Scottish Gaelic", "native" => "Scottish Gaelic", "id" => 102),
    "sr" => array("name" => "Serbian - српски", "native" => "српски", "id" => 103),
    "sh" => array("name" => "Serbo - Croatian", "native" => "Croatian", "id" => 104),
    "sn" => array("name" => "Shona - chiShona", "native" => "chiShona", "id" => 105),
    "sd" => array("name" => "Sindhi", "native" => "Sindhi", "id" => 106),
    "si" => array("name" => "Sinhala - සිංහල", "native" => "සිංහල", "id" => 107),
    "sk" => array("name" => "Slovak - slovenčina", "native" => "slovenčina", "id" => 108),
    "sl" => array("name" => "Slovenian - slovenščina", "native" => "slovenščina", "id" => 109),
    "so" => array("name" => "Somali - Soomaali", "native" => "Soomaali", "id" => 110),
    "st" => array("name" => "Southern Sotho", "native" => "Southern Sotho", "id" => 111),
    "es" => array("name" => "Spanish - español", "native" => "español", "id" => 112),
    "es-AR" => array("name" => "Spanish (Argentina) - español (Argentina)", "native" => "español (Argentina)", "id" => 113),
    "es-419" => array("name" => "Spanish (Latin America) - español (Latinoamérica)", "native" => "español (Latinoamérica)", "id" => 114),
    "es-MX" => array("name" => "Spanish (Mexico) - español (México)", "native" => "español (México)", "id" => 115),
    "es-ES" => array("name" => "Spanish (Spain) - español (España)", "native" => "español (España)", "id" => 116),
    "es-US" => array("name" => "Spanish (United States) - español (Estados Unidos)", "native" => "español (Estados Unidos)", "id" => 117),
    "su" => array("name" => "Sundanese", "native" => "Sundanese", "id" => 118),
    "sw" => array("name" => "Swahili - Kiswahili", "native" => "Kiswahili", "id" => 119),
    "sv" => array("name" => "Swedish - svenska", "native" => "svenska", "id" => 120),
    "tg" => array("name" => "Tajik - тоҷикӣ", "native" => "тоҷикӣ", "id" => 121),
    "ta" => array("name" => "Tamil - தமிழ்", "native" => "தமிழ்", "id" => 122),
    "tt" => array("name" => "Tatar", "native" => "Tatar", "id" => 123),
    "te" => array("name" => "Telugu - తెలుగు", "native" => "తెలుగు", "id" => 124),
    "th" => array("name" => "Thai - ไทย", "native" => "ไทย", "id" => 125),
    "ti" => array("name" => "Tigrinya - ትግርኛ", "native" => "ትግርኛ", "id" => 126),
    "to" => array("name" => "Tongan - lea fakatonga", "native" => "lea fakatonga", "id" => 127),
    "tr" => array("name" => "Turkish - Türkçe", "native" => "Türkçe", "id" => 128),
    "tk" => array("name" => "Turkmen", "native" => "Turkmen", "id" => 129),
    "tw" => array("name" => "Twi", "native" => "Twi", "id" => 130),
    "uk" => array("name" => "Ukrainian - українська", "native" => "українська", "id" => 131),
    "ur" => array("name" => "Urdu - اردو", "native" => "اردو", "id" => 132),
    "ug" => array("name" => "Uyghur", "native" => "Uyghur", "id" => 133),
    "uz" => array("name" => "Uzbek - o‘zbek", "native" => "o‘zbek", "id" => 134),
    "vi" => array("name" => "Vietnamese - Tiếng Việt", "native" => "Tiếng Việt", "id" => 135),
    "wa" => array("name" => "Walloon - wa", "native" => "wa", "id" => 136),
    "cy" => array("name" => "Welsh - Cymraeg", "native" => "Cymraeg", "id" => 137),
    "fy" => array("name" => "Western Frisian", "native" => "Western Frisian", "id" => 138),
    "xh" => array("name" => "Xhosa", "native" => "Xhosa", "id" => 139),
    "yi" => array("name" => "Yiddish", "native" => "Yiddish", "id" => 140),
    "yo" => array("name" => "Yoruba - Èdè Yorùbá", "native" => "Èdè Yorùbá", "id" => 141),
    "zu" => array("name" => "Zulu - isiZulu", "native" => "isiZulu", "id" => 142)
);
?>