<?php
// count 168
return array(
    "AFA" => array("name" => "Afghan Afghani", "symbol" => "؋", "id" => 1),
    "ALL" => array("name" => "Albanian Lek", "symbol" => "Lek", "id" => 2),
    "DZD" => array("name" => "Algerian Dinar", "symbol" => "دج", "id" => 3),
    "AOA" => array("name" => "Angolan Kwanza", "symbol" => "Kz", "id" => 4),
    "ARS" => array("name" => "Argentine Peso", "symbol" => "$", "id" => 5),
    "AMD" => array("name" => "Armenian Dram", "symbol" => "֏", "id" => 6),
    "AWG" => array("name" => "Aruban Florin", "symbol" => "ƒ", "id" => 7),
    "AUD" => array("name" => "Australian Dollar", "symbol" => "$", "id" => 8),
    "AZN" => array("name" => "Azerbaijani Manat", "symbol" => "m", "id" => 9),
    "BSD" => array("name" => "Bahamian Dollar", "symbol" => "B$", "id" => 10),
    "BHD" => array("name" => "Bahraini Dinar", "symbol" => ".د.ب", "id" => 11),
    "BDT" => array("name" => "Bangladeshi Taka", "symbol" => "৳", "id" => 12),
    "BBD" => array("name" => "Barbadian Dollar", "symbol" => "Bds$", "id" => 13),
    "BYR" => array("name" => "Belarusian Ruble", "symbol" => "Br", "id" => 14),
    "BEF" => array("name" => "Belgian Franc", "symbol" => "fr", "id" => 15),
    "BZD" => array("name" => "Belize Dollar", "symbol" => "$", "id" => 16),
    "BMD" => array("name" => "Bermudan Dollar", "symbol" => "$", "id" => 17),
    "BTN" => array("name" => "Bhutanese Ngultrum", "symbol" => "Nu.", "id" => 18),
    "BTC" => array("name" => "Bitcoin", "symbol" => "฿", "id" => 19),
    "BOB" => array("name" => "Bolivian Boliviano", "symbol" => "Bs.", "id" => 20),
    "BAM" => array("name" => "Bosnia-Herzegovina Convertible Mark", "symbol" => "KM", "id" => 21),
    "BWP" => array("name" => "Botswanan Pula", "symbol" => "P", "id" => 22),
    "BRL" => array("name" => "Brazilian Real", "symbol" => "R$", "id" => 23),
    "GBP" => array("name" => "British Pound Sterling", "symbol" => "£", "id" => 24),
    "BND" => array("name" => "Brunei Dollar", "symbol" => "B$", "id" => 25),
    "BGN" => array("name" => "Bulgarian Lev", "symbol" => "Лв.", "id" => 26),
    "BIF" => array("name" => "Burundian Franc", "symbol" => "FBu", "id" => 27),
    "KHR" => array("name" => "Cambodian Riel", "symbol" => "KHR", "id" => 28),
    "CAD" => array("name" => "Canadian Dollar", "symbol" => "$", "id" => 29),
    "CVE" => array("name" => "Cape Verdean Escudo", "symbol" => "$", "id" => 30),
    "KYD" => array("name" => "Cayman Islands Dollar", "symbol" => "$", "id" => 31),
    "XOF" => array("name" => "CFA Franc BCEAO", "symbol" => "CFA", "id" => 32),
    "XAF" => array("name" => "CFA Franc BEAC", "symbol" => "FCFA", "id" => 33),
    "XPF" => array("name" => "CFP Franc", "symbol" => "₣", "id" => 34),
    "CLP" => array("name" => "Chilean Peso", "symbol" => "$", "id" => 35),
    "CLF" => array("name" => "Chilean Unit of Account", "symbol" => "CLF", "id" => 36),
    "CNY" => array("name" => "Chinese Yuan", "symbol" => "¥", "id" => 37),
    "COP" => array("name" => "Colombian Peso", "symbol" => "$", "id" => 38),
    "KMF" => array("name" => "Comorian Franc", "symbol" => "CF", "id" => 39),
    "CDF" => array("name" => "Congolese Franc", "symbol" => "FC", "id" => 40),
    "CRC" => array("name" => "Costa Rican Colón", "symbol" => "₡", "id" => 41),
    "HRK" => array("name" => "Croatian Kuna", "symbol" => "kn", "id" => 42),
    "CUC" => array("name" => "Cuban Convertible Peso", "symbol" => "$, CUC", "id" => 43),
    "CZK" => array("name" => "Czech Republic Koruna", "symbol" => "Kč", "id" => 44),
    "DKK" => array("name" => "Danish Krone", "symbol" => "Kr.", "id" => 45),
    "DJF" => array("name" => "Djiboutian Franc", "symbol" => "Fdj", "id" => 46),
    "DOP" => array("name" => "Dominican Peso", "symbol" => "$", "id" => 47),
    "XCD" => array("name" => "East Caribbean Dollar", "symbol" => "$", "id" => 48),
    "EGP" => array("name" => "Egyptian Pound", "symbol" => "ج.م", "id" => 49),
    "ERN" => array("name" => "Eritrean Nakfa", "symbol" => "Nfk", "id" => 50),
    "EEK" => array("name" => "Estonian Kroon", "symbol" => "kr", "id" => 51),
    "ETB" => array("name" => "Ethiopian Birr", "symbol" => "Nkf", "id" => 52),
    "EUR" => array("name" => "Euro", "symbol" => "€", "id" => 53),
    "FKP" => array("name" => "Falkland Islands Pound", "symbol" => "£", "id" => 54),
    "FJD" => array("name" => "Fijian Dollar", "symbol" => "FJ$", "id" => 55),
    "GMD" => array("name" => "Gambian Dalasi", "symbol" => "D", "id" => 56),
    "GEL" => array("name" => "Georgian Lari", "symbol" => "ლ", "id" => 57),
    "DEM" => array("name" => "German Mark", "symbol" => "DM", "id" => 58),
    "GHS" => array("name" => "Ghanaian Cedi", "symbol" => "GH₵", "id" => 59),
    "GIP" => array("name" => "Gibraltar Pound", "symbol" => "£", "id" => 60),
    "GRD" => array("name" => "Greek Drachma", "symbol" => "₯, Δρχ, Δρ", "id" => 61),
    "GTQ" => array("name" => "Guatemalan Quetzal", "symbol" => "Q", "id" => 62),
    "GNF" => array("name" => "Guinean Franc", "symbol" => "FG", "id" => 63),
    "GYD" => array("name" => "Guyanaese Dollar", "symbol" => "$", "id" => 64),
    "HTG" => array("name" => "Haitian Gourde", "symbol" => "G", "id" => 65),
    "HNL" => array("name" => "Honduran Lempira", "symbol" => "L", "id" => 66),
    "HKD" => array("name" => "Hong Kong Dollar", "symbol" => "$", "id" => 67),
    "HUF" => array("name" => "Hungarian Forint", "symbol" => "Ft", "id" => 68),
    "ISK" => array("name" => "Icelandic Króna", "symbol" => "kr", "id" => 69),
    "INR" => array("name" => "Indian Rupee", "symbol" => "₹", "id" => 70),
    "IDR" => array("name" => "Indonesian Rupiah", "symbol" => "Rp", "id" => 71),
    "IRR" => array("name" => "Iranian Rial", "symbol" => "﷼", "id" => 72),
    "IQD" => array("name" => "Iraqi Dinar", "symbol" => "د.ع", "id" => 73),
    "ILS" => array("name" => "Israeli New Sheqel", "symbol" => "₪", "id" => 74),
    "ITL" => array("name" => "Italian Lira", "symbol" => "L,£", "id" => 75),
    "JMD" => array("name" => "Jamaican Dollar", "symbol" => "J$", "id" => 76),
    "JPY" => array("name" => "Japanese Yen", "symbol" => "¥", "id" => 77),
    "JOD" => array("name" => "Jordanian Dinar", "symbol" => "ا.د", "id" => 78),
    "KZT" => array("name" => "Kazakhstani Tenge", "symbol" => "лв", "id" => 79),
    "KES" => array("name" => "Kenyan Shilling", "symbol" => "KSh", "id" => 80),
    "KWD" => array("name" => "Kuwaiti Dinar", "symbol" => "ك.د", "id" => 81),
    "KGS" => array("name" => "Kyrgystani Som", "symbol" => "лв", "id" => 82),
    "LAK" => array("name" => "Laotian Kip", "symbol" => "₭", "id" => 83),
    "LVL" => array("name" => "Latvian Lats", "symbol" => "Ls", "id" => 84),
    "LBP" => array("name" => "Lebanese Pound", "symbol" => "£", "id" => 85),
    "LSL" => array("name" => "Lesotho Loti", "symbol" => "L", "id" => 86),
    "LRD" => array("name" => "Liberian Dollar", "symbol" => "$", "id" => 87),
    "LYD" => array("name" => "Libyan Dinar", "symbol" => "د.ل", "id" => 88),
    "LTC" => array("name" => "Litecoin", "symbol" => "Ł", "id" => 89),
    "LTL" => array("name" => "Lithuanian Litas", "symbol" => "Lt", "id" => 90),
    "MOP" => array("name" => "Macanese Pataca", "symbol" => "$", "id" => 91),
    "MKD" => array("name" => "Macedonian Denar", "symbol" => "ден", "id" => 92),
    "MGA" => array("name" => "Malagasy Ariary", "symbol" => "Ar", "id" => 93),
    "MWK" => array("name" => "Malawian Kwacha", "symbol" => "MK", "id" => 94),
    "MYR" => array("name" => "Malaysian Ringgit", "symbol" => "RM", "id" => 95),
    "MVR" => array("name" => "Maldivian Rufiyaa", "symbol" => "Rf", "id" => 96),
    "MRO" => array("name" => "Mauritanian Ouguiya", "symbol" => "MRU", "id" => 97),
    "MUR" => array("name" => "Mauritian Rupee", "symbol" => "₨", "id" => 98),
    "MXN" => array("name" => "Mexican Peso", "symbol" => "$", "id" => 99),
    "MDL" => array("name" => "Moldovan Leu", "symbol" => "L", "id" => 100),
    "MNT" => array("name" => "Mongolian Tugrik", "symbol" => "₮", "id" => 101),
    "MAD" => array("name" => "Moroccan Dirham", "symbol" => "MAD", "id" => 102),
    "MZM" => array("name" => "Mozambican Metical", "symbol" => "MT", "id" => 103),
    "MMK" => array("name" => "Myanmar Kyat", "symbol" => "K", "id" => 104),
    "NAD" => array("name" => "Namibian Dollar", "symbol" => "$", "id" => 105),
    "NPR" => array("name" => "Nepalese Rupee", "symbol" => "₨", "id" => 106),
    "ANG" => array("name" => "Netherlands Antillean Guilder", "symbol" => "ƒ", "id" => 107),
    "TWD" => array("name" => "New Taiwan Dollar", "symbol" => "$", "id" => 108),
    "NZD" => array("name" => "New Zealand Dollar", "symbol" => "$", "id" => 109),
    "NIO" => array("name" => "Nicaraguan Córdoba", "symbol" => "C$", "id" => 110),
    "NGN" => array("name" => "Nigerian Naira", "symbol" => "₦", "id" => 111),
    "KPW" => array("name" => "North Korean Won", "symbol" => "₩", "id" => 112),
    "NOK" => array("name" => "Norwegian Krone", "symbol" => "kr", "id" => 113),
    "OMR" => array("name" => "Omani Rial", "symbol" => ".ع.ر", "id" => 114),
    "PKR" => array("name" => "Pakistani Rupee", "symbol" => "₨", "id" => 115),
    "PAB" => array("name" => "Panamanian Balboa", "symbol" => "B/.", "id" => 116),
    "PGK" => array("name" => "Papua New Guinean Kina", "symbol" => "K", "id" => 117),
    "PYG" => array("name" => "Paraguayan Guarani", "symbol" => "₲", "id" => 118),
    "PEN" => array("name" => "Peruvian Nuevo Sol", "symbol" => "S/.", "id" => 119),
    "PHP" => array("name" => "Philippine Peso", "symbol" => "₱", "id" => 120),
    "PLN" => array("name" => "Polish Zloty", "symbol" => "zł", "id" => 121),
    "QAR" => array("name" => "Qatari Rial", "symbol" => "ق.ر", "id" => 122),
    "RON" => array("name" => "Romanian Leu", "symbol" => "lei", "id" => 123),
    "RUB" => array("name" => "Russian Ruble", "symbol" => "₽", "id" => 124),
    "RWF" => array("name" => "Rwandan Franc", "symbol" => "FRw", "id" => 125),
    "SVC" => array("name" => "Salvadoran Colón", "symbol" => "₡", "id" => 126),
    "WST" => array("name" => "Samoan Tala", "symbol" => "SAT", "id" => 127),
    "STD" => array("name" => "São Tomé and Príncipe Dobra", "symbol" => "Db", "id" => 128),
    "SAR" => array("name" => "Saudi Riyal", "symbol" => "﷼", "id" => 129),
    "RSD" => array("name" => "Serbian Dinar", "symbol" => "din", "id" => 130),
    "SCR" => array("name" => "Seychellois Rupee", "symbol" => "SRe", "id" => 131),
    "SLL" => array("name" => "Sierra Leonean Leone", "symbol" => "Le", "id" => 132),
    "SGD" => array("name" => "Singapore Dollar", "symbol" => "$", "id" => 133),
    "SKK" => array("name" => "Slovak Koruna", "symbol" => "Sk", "id" => 134),
    "SBD" => array("name" => "Solomon Islands Dollar", "symbol" => "Si$", "id" => 135),
    "SOS" => array("name" => "Somali Shilling", "symbol" => "Sh.so.", "id" => 136),
    "ZAR" => array("name" => "South African Rand", "symbol" => "R", "id" => 137),
    "KRW" => array("name" => "South Korean Won", "symbol" => "₩", "id" => 138),
    "SSP" => array("name" => "South Sudanese Pound", "symbol" => "£", "id" => 139),
    "XDR" => array("name" => "Special Drawing Rights", "symbol" => "SDR", "id" => 140),
    "LKR" => array("name" => "Sri Lankan Rupee", "symbol" => "Rs", "id" => 141),
    "SHP" => array("name" => "St. Helena Pound", "symbol" => "£", "id" => 142),
    "SDG" => array("name" => "Sudanese Pound", "symbol" => ".س.ج", "id" => 143),
    "SRD" => array("name" => "Surinamese Dollar", "symbol" => "$", "id" => 144),
    "SZL" => array("name" => "Swazi Lilangeni", "symbol" => "E", "id" => 145),
    "SEK" => array("name" => "Swedish Krona", "symbol" => "kr", "id" => 146),
    "CHF" => array("name" => "Swiss Franc", "symbol" => "CHf", "id" => 147),
    "SYP" => array("name" => "Syrian Pound", "symbol" => "LS", "id" => 148),
    "TJS" => array("name" => "Tajikistani Somoni", "symbol" => "SM", "id" => 149),
    "TZS" => array("name" => "Tanzanian Shilling", "symbol" => "TSh", "id" => 150),
    "THB" => array("name" => "Thai Baht", "symbol" => "฿", "id" => 151),
    "TOP" => array("name" => "Tongan Pa'anga", "symbol" => "$", "id" => 152),
    "TTD" => array("name" => "Trinidad & Tobago Dollar", "symbol" => "$", "id" => 153),
    "TND" => array("name" => "Tunisian Dinar", "symbol" => "ت.د", "id" => 154),
    "TRY" => array("name" => "Turkish Lira", "symbol" => "₺", "id" => 155),
    "TMT" => array("name" => "Turkmenistani Manat", "symbol" => "T", "id" => 156),
    "UGX" => array("name" => "Ugandan Shilling", "symbol" => "USh", "id" => 157),
    "UAH" => array("name" => "Ukrainian Hryvnia", "symbol" => "₴", "id" => 158),
    "AED" => array("name" => "United Arab Emirates Dirham", "symbol" => "إ.د", "id" => 159),
    "UYU" => array("name" => "Uruguayan Peso", "symbol" => "$", "id" => 160),
    "USD" => array("name" => "US Dollar", "symbol" => "$", "id" => 161),
    "UZS" => array("name" => "Uzbekistan Som", "symbol" => "лв", "id" => 162),
    "VUV" => array("name" => "Vanuatu Vatu", "symbol" => "VT", "id" => 163),
    "VEF" => array("name" => "Venezuelan BolÃvar", "symbol" => "Bs", "id" => 164),
    "VND" => array("name" => "Vietnamese Dong", "symbol" => "₫", "id" => 165),
    "YER" => array("name" => "Yemeni Rial", "symbol" => "﷼", "id" => 166),
    "ZMK" => array("name" => "Zambian Kwacha", "symbol" => "ZK", "id" => 167),
    "ZWL" => array("name" => "Zimbabwean dollar", "symbol" => "$", "id" => 168)
);
?>